name: Build ARM64 Kernel

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARCH: arm64
      SUBARCH: arm64
      CROSS_COMPILE: ${{ github.workspace }}/toolchain/aarch64-linux-android-4.9-toolchain/bin/aarch64-linux-android-
      OUTPUT_DIR: ${{ github.workspace }}/out

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential bc bison flex git curl zip unzip cpio python3 python3-pip libncurses5-dev libssl-dev wget libelf-dev fakeroot

    - name: Create output directory
      run: mkdir -p $OUTPUT_DIR

    - name: Build   
      run: |
        make -j$(nproc) -C ${{ github.workspace }} O=$OUTPUT_DIR \
          DTC_EXT=${{ github.workspace }}/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y \
          ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE \
          vendor/r9q_eur_openx2_defconfig
        make -j$(nproc) -C ${{ github.workspace }} O=$OUTPUT_DIR \
          DTC_EXT=${{ github.workspace }}/tools/dtc CONFIG_BUILD_ARM64_DT_OVERLAY=y \
          ARCH=arm64 CROSS_COMPILE=$CROSS_COMPILE

    - name: Upload kernel Image artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel-image
        path: ${{ env.OUTPUT_DIR }}/arch/arm64/boot/Image
